//
//  CatalpgViewModel.swift
//  FMCGApp
//
//  Created by Анастасия on 09.08.2024.
//

import Foundation

final class CatalogViewModel: ObservableObject {
    @Published var products: [Product] = [
            Product(name: "test1",
                    image: "Card_image_1",
                    price: 30.99,
                    discount: nil,
                    badge: "badge1",
                    isLiked: false,
                    rating: 4.1,
                    isCountable: false,
                    defaultCountForOneItem: 0.88,
                    pickedItems: nil,
                    countryOfProduction: "Франция 🇫🇷",
                    reviews: 19),
            Product(name: "test2",
                    image: "Card_image_2",
                    price: 990.99,
                    discount: 0.1099,
                    badge: nil,
                    isLiked: false,
                    rating: 4.9,
                    isCountable: false,
                    defaultCountForOneItem: 0.18,
                    pickedItems: 1,
                    countryOfProduction: nil,
                    reviews: 20),
            Product(name: "test1",
                    image: "Card_image_3",
                    price: 99.99,
                    discount: 0.055,
                    badge: "badge2",
                    isLiked: true,
                    rating: 4.0,
                    isCountable: false,
                    defaultCountForOneItem: 0.33,
                    pickedItems: 1,
                    countryOfProduction: nil,
                    reviews: 19),
            Product(name: "test4",
                    image: "Card_image_4",
                    price: 30.99,
                    discount: nil,
                    badge: "badge1",
                    isLiked: false,
                    rating: 4.1,
                    isCountable: false,
                    defaultCountForOneItem: 0.11,
                    pickedItems: nil,
                    countryOfProduction: nil,
                    reviews: 19),
            Product(name: "test5",
                    image: "Card_image_5",
                    price: 450.99,
                    discount: nil,
                    badge: "badge3",
                    isLiked: true,
                    rating: nil,
                    isCountable: false,
                    defaultCountForOneItem: 0.23,
                    pickedItems: 2,
                    countryOfProduction: "Франция 🇫🇷",
                    reviews: nil),
            Product(name: "test6",
                    image: "Card_image_6",
                    price: 3440.99,
                    discount: 0.30,
                    badge: nil,
                    isLiked: true,
                    rating: 3.8,
                    isCountable: false,
                    defaultCountForOneItem: 0.118,
                    pickedItems: nil,
                    countryOfProduction: nil,
                    reviews: 20),
            Product(name: "test test test testtest test test testtest test test testtest test test test",
                    image: "Card_image_1",
                    price: 440.99,
                    discount: nil,
                    badge: "badge3",
                    isLiked: true,
                    rating: 4.8,
                    isCountable: false,
                    defaultCountForOneItem: 0.1,
                    pickedItems: nil,
                    countryOfProduction: "Франция 🇫🇷",
                    reviews: 2)
        ]
}
